mysql:
  JWT_LEEWAY: 604800
  SECRET_KEY: '7PXsHcHGfa4e3kEs8Rvcv8ymjI0UeauX'
  # SECRET_KEY = os.environ.get('SECRET_KEY') or 'hard to guess'
  DIALECT: 'mysql'
  DRIVER: 'pymysql'
  USERNAME: 'kylezhao'
  PASSWORD: '123456'
  HOST: '47.93.199.183'
  PORT: '3306'
  DATABASE: 'test'
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  SQLALCHEMY_COMMIT_ON_TEARDOWN: True
  SQLALCHEMY_POOL_SIZE: 10
  SQLALCHEMY_MAX_OVERFLOW: 5
rbb:
  sheet0: 
    name: 日报计算表
    start_row: 5
    end_row: 371
    start_col: A
    end_col: BX
    skip_row: []
    merge_row: []
    date_col: A
    fka_312_col: B
    bka_312_col: C
    fka_313_col: D
    bka_313_col: E
    fka_322_col: F
    bka_322_col: G
    fka_323_col: H
    bka_323_col: I
    fka_31b_col: J
    fka_21b_col: K
    fka_311_col: L
    bka_311_col: M
    fkr_311_col: N
    bkr_311_col: O
    fka_321_col: P
    bka_321_col: Q
    fkr_321_col: R
    bkr_321_col: S
    bka_111_col: T
    fka_111_col: U
    dgp1_col: V
    donp1_col: W
    doffp1_col: X
    dcp1_col: Y
    dcl1_col: Z
    dgp2_col: AA
    donp2_col: AB
    doffp2_col: AC
    dcp2_col: AD
    dcl2_col: AE
    dgp_col: AF
    donp_col: AG
    doffp_col: AH
    dcp_col: AI
    dcl_col: AJ
    doffp_31b_col: AK
    doffp_21b_col: AL
    agp1_col: AM
    aonp1_col: AN
    aoffp1_col: AO
    acp1_col: AP
    acl1_col: AQ
    agp2_col: AR
    aonp2_col: AS
    aoffp2_col: AT
    acp2_col: AU
    acl2_col: AV
    agp_col: AW
    aonp_col: AX
    aoffp_col: AY
    acp_col: AZ
    acl_col: BA
    mgp1_col: BB
    monp1_col: BC
    moffp1_col: BD
    mcp1_col: BE
    mcl1_col: BF
    mgp2_col: BG
    monp2_col: BH
    moffp2_col: BI
    mcp2_col: BJ
    mcl2_col: BK
    mgp_col: BL
    monp_col: BM
    moffp_col: BN
    mcp_col: BO
    mcl_col: BP
    donja_311_col: BQ
    doffja_311_col: BR
    donjr_311_col: BS
    doffjr_311_col: BT
    donja_321_col: BU
    doffja_321_col: BV
    donjr_321_col: BW
    doffjr_321_col: BX
  sheet1: 
    name: 风机维护统计
    skip_1_row: null
    wt_id_1_col: A
    wtm_type_1_col: B
    wtm_task_1_col: C
    wt_down_time_1_col: D
    wt_up_time_1_col: F
    wtm_time_1_col: G
    wtm_lost_power_1_col: H
    skip_2_row: null
    wt_id_2_col: I
    wtm_type_2_col: J
    wtm_task_2_col: K
    wt_down_time_2_col: L
    wt_up_time_2_col: M
    wtm_time_2_col: N
    wtm_lost_power_2_col: O
  sheet2: 
    name: 风机故障统计
    skip_1_row: null
    wt_id_1_col: A
    err_code_1_col: B
    err_content_1_col: C
    err_type_1_col: D
    wt_down_time_1_col: E
    wt_up_time_1_col: F
    err_time_1_col: G
    err_lost_power_1_col: H
    err_approach_1_col: I
    skip_2_row: null
    wt_id_2_col: K
    err_code_2_col: L
    err_content_2_col: M
    err_type_2_col: N
    wt_down_time_2_col: O
    wt_up_time_2_col: P
    err_time_2_col: Q
    err_lost_power_2_col: R
    err_approach_2_col: S
  sheet3:
    name: 输变电故障、维护统计
    range_1_col: A
    content_1_col: B
    process_1_col: C
    start_time_1_col: D
    stop_time_1_col: E
    time_1_col: F
    lost_power_1_col: G
    range_2_col: I
    content_2_col: J
    process_2_col: K
    start_time_2_col: L
    stop_time_2_col: M
    time_2_col: N
    lost_power_2_col: O
  sheet4: 
    sheet_name: 电网故障、检修、限电统计
    range_1_col: A
    type_1_col: B
    wt_id_1_col: C
    content_1_col: D
    start_time_1_col: E
    stop_time_1_col: F
    time_1_col: G
    lost_power_1_col: H
    range_2_col: K
    type_2_col: L
    wt_id_2_col: M
    start_time_2_col: N
    stop_time_2_col: O
    time_2_col: P
    lost_power_2_col: Q
dlfs: 
  dir: /Users/kyle/Desktop
  name: 石桥风电场报送每日风机电量风速统计表 2021.xlsx
  sheet1: 
    name: 风速统计
    start_row: 3
    end_row: 367
    start_col: A
    end_col: C
    date_col: A
    wind_speed_1_col: B
    wind_speed_2_col: C
gdr:
  dir: /Users/kyle/Desktop
  name: 生产运行情况日报表-temp.xlsx
  sheet0:
    name: 发电生产情况日报（风电）
#    运行容量
    yxrl_row: 13
    yxrl_col: F
#    检修容量
    jxrl_row: 13
    jxrl_col: G
#    备用容量
    byrl_row: 13
    byrl_col: H
#    临检容量
    ljrl_row: 13
    ljrl_col: I
#    新增容量
    xzrl_row: 13
    xzrl_col: J
#    发电量
    fdl_row: 13
    fdl_col: K
#    试运行发电量
    syxfdl_row: 13
    syxfdl_col: L
#    综合厂用电量
    zhcydl_row: 13
    zhcydl_col: N
#    发电厂用电量
    fdcydl_row: 13
    fdcydl_col: P
#    上网电量-合计
    swdl_hj_row: 13
    swdl_hj_col: R
#    上网电量-基数外
    swdl_jsw_row: 12
    swdl_jsw_col: T
#    被替代售电量
    btdsdl_row: 12
    btdsdl_col: U
#    网购电量
    wgdl_row: 12
    wgdl_col: V
#    平均风速
    pjfs_row: 13
    pjfs_col: W
#     限电量
    xdl_row: 13
    xdl_col: X
#    上网电价-基数内
    swdj_jsn_row: 12
    swdj_jsn_col: AA
#    上网电价-基数外
    swdj_jsw_row: 12
    swdj_jsw_col: AB
#    被替代售电价
    btdsdj_row: 12
    btdsdj_col: AC
#    购电单价
    gddj_row: 12
    gddj_col: AD
#    可用小时
    kyxs_row: 13
    kyxs_col: AE
#    计划停运小时
    jhtyxs_row: 13
    jhtyxs_col: AG
#    非计划停运小时
    fjhtyxs_row: 13
    fjhtyxs_col: AH
#    非计划损失电量
    fjhssdl_row: 13
    fjhssdl_col: AI
#    平均风速预测
    pjfsyc_row: 13
    pjfsyc_col: AK
#    日功率预测
    rglyc_row: 13
    rglyc_col: AL